---
output: html_document
---
## Human Activity Recognition Using Smartphones Dataset Version 1.0
### Pedro Marquez
### February  2015


A series of experiments have been carried out with a group of 30 volunteers within an age bracket of 19-48 years. Each person performed six activities (**WALKING**, **WALKING_UPSTAIRS**, **WALKING_DOWNSTAIRS**, **SITTING**, **STANDING**, **LAYING**) wearing a smartphone (Samsung Galaxy S II) on the waist. Using its embedded accelerometer and gyroscope, we captured 3-axial linear acceleration and 3-axial angular velocity at a constant rate of 50Hz. The experiments have been video-recorded to label the data manually. The obtained dataset has been randomly partitioned into two sets, where 70% of the volunteers was selected for generating the training data and 30% the test data. 


The sensor signals (accelerometer and gyroscope) were pre-processed by applying noise filters and then sampled in fixed-width sliding windows of 2.56 sec and 50% overlap (128 readings/window). The sensor acceleration signal, which has gravitational and body motion components, was separated using a Butterworth low-pass filter into body acceleration and gravity. The gravitational force is assumed to have only low frequency components, therefore a filter with 0.3 Hz cutoff frequency was used. From each window, a vector of features was obtained by calculating variables from the time and frequency domain. See **features_info.txt** for more details. 


For each record it is provided:

* Triaxial acceleration from the accelerometer (total acceleration) and the estimated body acceleration.
* Triaxial Angular velocity from the gyroscope. 
* A 561-feature vector with time and frequency domain variables. 
* Its activity label. 
* An identifier of the subject who carried out the experiment.


The dataset includes the following files:

* **README.txt**: This file.

* **features_info.txt**: Shows information about the variables used on the feature vector.

* **features.txt**: List of all features.

* **activity_labels.txt**: Links the class labels with their activity name.

* **train/X_train.txt**: Training set.

* **train/Y_train.txt**: Training labels.

* **test/X_test.txt**: Test set.

* **test/Y_test.txt**: Test labels.


The following files are available for the train and test data. Their descriptions are equivalent. 

* **train/subject_train.txt**: Each row identifies the subject who performed the activity for each window sample. Its range is from 1 to 30. 

* **train/Inertial_Signals/total_acc_x_train.txt**: The acceleration signal from the smartphone accelerometer X axis in standard gravity units 'g'. Every row shows a 128 element vector. The same description applies for the 'total_acc_x_train.txt' and 'total_acc_z_train.txt' files for the Y and Z axis. 

* **train/Inertial Signals/body_acc_x_train.txt**: The body acceleration signal obtained by subtracting the gravity from the total acceleration. 

* **train/Inertial Signals/body_gyro_x_train.txt**: The angular velocity vector measured by the gyroscope for each window sample. The units are radians/second.


This dataset has been reported in [1].

[1] Davide Anguita, Alessandro Ghio, Luca Oneto, Xavier Parra and Jorge L. Reyes-Ortiz. Human Activity Recognition on Smartphones using a Multiclass Hardware-Friendly Support Vector Machine. International Workshop of Ambient Assisted Living (IWAAL 2012). Vitoria-Gasteiz, Spain. Dec 2012



Program Requirements
====================

The program should do basically the following:

1. Merge the __training__ and the __test__ sets to create one data set.
2. Extract only the measurements on the __mean__ and __standard deviation__ for each measurement.
3. Use descriptive activity names to name the activities in the data set
4. Appropriately label the data set with descriptive variable names.
5. From the data set in step 4, create a second, independent tidy data set with the _average_ of each variable for each activity and each subject.

Tables Returned
===============

The program basically creates two tables, although it creates other ancillary
tables in the process. The "end" tables created by the program have been named
`data_tbl` and `smy_tbl`. The first one contains all information from the training
data set, while the second one contains the summary of all "mean" and "standard deviation"
features averaged by subject and activity.

Program Code Explanation
========================

The following link takes you to a detailed explanation of the program's code:
[Interactive code explanation](run_analysis.Rmd)

